### ISSUE TITLE
error with getting client credentials on initialisation:

### ISSUE THREAD

**Issue by joshuamilo** [kvithana/spotify-audio-analysis-to-csv#1]
Hey there!

I entered my Spotify Client ID & Client Secret into the .env file but I am getting the following error when I try to run the import script. 

```
Joshua:spotify-audio-features-to-csv-master joshuabehrends$ npm run import

> spotify-analysis-csv@1.0.0 import
> tsc && node build/main.js

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: error with getting client credentials on initialisation: WebapiError: Bad Request] {
  data: {
    message: 'error with getting client credentials on initialisation:'
  }
}
```

I tried entering the client keys with ', " or without quotation marks.
Sorry, I am kind of a programming noob.

All the best,
Joshua

**Comment by kvithana** [comment]
Hi Joshua

Sorry I only saw this just now! Hope you managed to figure it out. Feel free to reach out if you ever need help with the Spotify API.
